redis:
  image: rancher/external-service
logstash-collector-config:
  labels:
    io.rancher.container.hostname_override: container_name
  image: rancher/logstash-config:v0.2.0
  links:
  - 'redis:'
logstash-collector:
  labels:
    io.rancher.sidekicks: logstash-collector-config
    io.rancher.container.hostname_override: container_name
  command:
    - logstash
    - -f
    - /etc/logstash
  image: logstash:2.1.1-1
  environment:
    LOGSPOUT: ignore
  links:
    - 'redis:'
  volumes_from:
    - logstash-collector-config
logspout:
  restart: always
  environment:
    ROUTE_URIS: logstash://logstash:5000
    LOGSPOUT: ignore
  links:
    - logstash-collector:logstash
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.hostname_override: container_name
  image: rancher/logspout-logstash:v0.2.0
logstash-lb:
  ports:
    - 5044:5044/tcp
  links:
    - logstash-collector:logstash-collector
  labels:
    io.rancher.loadbalancer.target.logstash-collector: 5044=5044
    io.rancher.scheduler.global: 'true'
  image: rancher/load-balancer-service
  environment:
    LOGSPOUT: ignore
